version: '3.5'

services:

    nginx:
      image: ${COMPOSE_PROJECT_NAME}_nginx:latest
      build:
        context: ./docker/
        args:
          BUILD_ARGUMENT_ENV: test
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - .:/var/www/html:ro,cached
      depends_on:
        - laravel
      networks:
        - laravel

    laravel: &laravel-template
      image: ${COMPOSE_PROJECT_NAME}_laravel:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: test
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_laravel
      volumes:
        - ./.git:/var/www/html/.git:cached
      depends_on:
        - mysql
      networks:
        - laravel

    ### Cron tasks
    supervisord:
      <<: *laravel-template
      container_name: ${COMPOSE_PROJECT_NAME}_supervisord
      expose: []
      command: ["/usr/bin/supervisord"]

    mysql:
      image: mysql:8.0
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: laravel
      ports:
        - "33061:3306"
      volumes:
        - ./storage/mysql-data:/var/lib/mysql:delegated
        - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      networks:
        - laravel

networks:
  laravel:
    name: laravel
